# Generated by Django 3.2.9 on 2022-01-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled'), ('Delayed', 'Delayed')], default='Upcoming', max_length=50, null=True),
        ),
    ]
