# Generated by Django 3.2.9 on 2021-12-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appoint_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
