# Generated by Django 3.2.9 on 2021-12-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20211213_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
