# Generated by Django 3.2.9 on 2021-12-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slug',
        ),
    ]
