# Generated by Django 3.2.9 on 2021-12-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('accounts', '0002_auto_20211206_0630'),
    ]

    operations = [
    ]
